image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "Mirror to GitHub without Jira tags and pipeline files"
        script:
          - set -x
          - git config --global user.name "Bitbucket Pipeline"
          - git config --global user.email "pipeline@example.com"
          - TEMP_DIR=$(mktemp -d)
          - git clone --mirror "$(pwd)" $TEMP_DIR
          - cd $TEMP_DIR
          - git fetch --all
          - git for-each-ref --format='%(refname:short)' refs/heads/ | while read branch; do
              echo "Processing branch: $branch"
              git checkout $branch
              COMMITS=$(git log --pretty=format:"%H")
              for commit in $COMMITS; do
                COMMIT_MSG=$(git log --format=%B -n 1 $commit)
                NEW_COMMIT_MSG=$(echo "$COMMIT_MSG" | sed -E 's/OPS-[0-9]+\s*//g')
                if [ "$COMMIT_MSG" != "$NEW_COMMIT_MSG" ]; then
                  echo "Updating commit message for $commit"
                  echo "Old: $COMMIT_MSG"
                  echo "New: $NEW_COMMIT_MSG"
                  git filter-branch --msg-filter "sed -E 's/OPS-[0-9]+\s*//g'" $commit^..$commit
                fi
              done
              git rm --cached bitbucket-pipelines.yml || true
              if ! git diff --cached --quiet; then
                git commit -m "Remove bitbucket-pipelines.yml for GitHub mirror"
              fi
            done
          - git for-each-ref --format='%(refname:short)' refs/heads/ | while read branch; do
              echo "Pushing branch $branch to GitHub..."
              git push --force https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/BlessedDayss/CaseNotifier.git $branch:$branch
            done