image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "Mirror to GitHub without Jira tag and pipelines file"
        script:
          - echo "Setting up global Git config..."
          - git config --global user.name "Bitbucket Pipeline"
          - git config --global user.email "pipeline@example.com"
          - echo "Creating temporary directory..."
          - TEMP_DIR=$(mktemp -d)
          - echo "Cloning repository (with working tree)..."
          - git clone "$(pwd)" $TEMP_DIR
          - cd $TEMP_DIR
          - echo "Fetching all refs..."
          - git fetch --all
          # Обработка каждой ветки
          - |
            for branch in $(git for-each-ref --format="%(refname:short)" refs/heads/); do
              echo "Processing branch: $branch"
              git checkout $branch
              echo "Rewriting commit messages in branch $branch..."
              git filter-branch --msg-filter "sed -E 's/OPS-[0-9]+\s*//g'" $branch
              # Удаляем файл bitbucket-pipelines.yml из индекса, чтобы он не попал в GitHub
              git rm --cached bitbucket-pipelines.yml || true
              # Если в индексе есть изменения, создаем коммит
              if ! git diff --cached --quiet; then
                git commit -m "Remove bitbucket-pipelines.yml for GitHub mirror"
              fi
            done
          # Пуш всех веток в GitHub
          - |
            for branch in $(git for-each-ref --format="%(refname:short)" refs/heads/); do
              echo "Pushing branch $branch to GitHub..."
              git push --force https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$GITHUB_USER/CaseNotifier.git $branch:$branch
            done
